//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_HowIMetYourMother.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personajes
    {
        public int ID { get; set; }
        public string NombrePersonaje { get; set; }
        public Nullable<int> TrabajoPersonaje { get; set; }
        public Nullable<int> EdadPrimeraTemporada { get; set; }
    }
}
